/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Pcbdb {
  new?: boolean;
  name?: string;
  sides?: number;
  width?: number;
  height?: number;
  cthickness?: number;
  bthickness?: number;
  [k: string]: unknown;
}
