/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserConfig {
  serial?: string;
  dialect?: string;
  units?: string;
  home?: boolean;
  feedrate?: number;
  precision?: number;
  linenumber?: boolean;
  archtolerance?: number;
  platewidth?: number;
  platedepth?: number;
  parkingx?: number;
  parkingy?: number;
  spindlespeed?: number;
  [k: string]: unknown;
}
