/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserConfig {
  choice?: string;
  home?: boolean;
  feedrate?: number;
  linenumber?: boolean;
  platewidth?: number;
  plateheight?: number;
  [k: string]: unknown;
}
