name: Audit Generator

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    name: NPM Audit (and fix)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Audit
        uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          project-path: "."
          fix: true
          package-lock-only: false
          force: false
          git-branch: npm-audit-action
          git-remote: origin
          github-token: ${{ secrets.github_token }} 
