name: Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # macos-11.0 ?
        os: [macos-latest , ubuntu-latest, windows-latest]
        arch: [x64]
#        arch: [ia32, armv7l, x64, arm64, mips64el]
        include:
        - os: macos-11.0
          arch: arm64
          experimental: true
        - os: windows-latest
          arch: ia32 
          experimantal: true
        - os: windows-latest
          arch: arm64 
          experimantal: true
      fail-fast: false


    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build/release Electron app
        run: |
          npm install
          npm run make -- --arch ${{ matrix.arch }}
      - name: nodejs project information
        id: projectinfo
        uses: gregoranders/nodejs-project-info@v0.0.12          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.projectinfo.outputs.name }}-${{ steps.projectinfo.outputs.version }}-${{ runner.os }}-${{ matrix.arch }}
          path: |
            out/make/**/${{ matrix.arch }}/*             
#            out/make/**/armv7l/*             
#            out/make/**/x64/*             
#            out/make/**/arm64/*  
#            out/make/**/mips64el/*             
