name: Release

on: 
  workflow_run:
    workflows: ["Build"]
    branch: [main]
    tags: 
      - v*
    types:
      - completed
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'      

jobs:        
  #Action only on release (tag starting with v)
  release:
#    if: startsWith(github.ref, 'refs/tags/v') 
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: nodejs project information
        id: projectinfo
        uses: gregoranders/nodejs-project-info@v0.0.12           
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          branch: main       
      - name: Debug Outputs
        env: 
          OUTPUT: ${{ needs.build.outputs}}
        run: echo "$OUTPUT"
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }} 
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: true
          prerelease: false  
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./**/*.exe;./**/*.rpm;./**/*.deb;./**/*.app;./**/*.dmg;./**/*.zip;./**/*.nupkg"
          tags: false
          draft: true
